export default defineAppConfig({
  authorCN: 'Startint',
  authorEN: 'Startint',
  title: 'jwwang.log',
  role: 'AI 应用开发工程师',
  status: '北京理工大学在读硕士',
  bio: '热爱 AI 技术，专注于 Agent、RAG 和知识图谱方向。具备扎实的数理基础和编程能力，善于独立解决问题并推动项目落地。',
  description: '记录 AI 应用开发、Agent 架构、RAG 系统和知识图谱的技术笔记。北京理工大学在读硕士。',
  github: 'https://github.com/jwwang2025',
  url: 'https://jwwang2025.github.io',
  friends: [],
  nav: [
    { label: '首页', path: '/' },
    { label: '文章', path: '/posts' },
    { label: '标签', path: '/tags' },
    { label: '关于', path: '/about' },
  ],
  techStack: [
    { name: 'Python', icon: '⬡' },
    { name: 'Java', icon: '⬡' },
    { name: 'LangChain', icon: '⬡' },
    { name: 'LangGraph', icon: '⬡' },
    { name: 'PyTorch', icon: '⬡' },
    { name: 'FastAPI', icon: '⬡' },
    { name: 'React', icon: '⬡' },
    { name: 'ChromaDB', icon: '⬡' },
    { name: 'Redis', icon: '⬡' },
    { name: 'LLM / Agent', icon: '⬡' },
  ],
  experience: [
    {
      company: '北京理工大学',
      companyEN: 'Beijing Institute of Technology',
      role: '硕士研究生',
      period: '2026.09 – 2029.06',
      desc: '计算机技术专业，研究方向为 AI 应用开发与智能系统。',
    },
    {
      company: '新疆大学',
      companyEN: 'Xinjiang University',
      role: '本科',
      period: '2022.09 – 2026.06',
      desc: '软件工程专业，GPA 3.93/5.0，排名前 4%。',
    },
  ],
  education: [],
})